steps:
  # ----------------------------------------------------------------------
  # 1. Fase de Integración Continua (CI): Formato, Inicialización y Validación
  # ----------------------------------------------------------------------
  - name: 'hashicorp/terraform:latest'
    id: 'terraform-fmt'
    args:
      - 'fmt'
      - '-recursive'
    dir: 'terraform'

  - name: 'hashicorp/terraform:latest'
    id: 'terraform-init'
    args:
      - 'init'
      - '-backend-config=bucket=${_TFSTATE_BUCKET}'
      - '-input=false'
    dir: 'terraform'

  - name: 'hashicorp/terraform:latest'
    id: 'terraform-workspace-select-or-new'
    entrypoint: 'sh'
    args:
      - '-c'
      - |
        terraform workspace select ${_ENV} || terraform workspace new ${_ENV}
    dir: 'terraform'

  - name: 'hashicorp/terraform:latest'
    id: 'terraform-validate'
    args:
      - 'validate'
      # La variable project_id no es necesaria para la validación de sintaxis, se elimina la flag -var
    dir: 'terraform'

  # ----------------------------------------------------------------------
  # 2. Fase de Despliegue (CD): Planificación
  # ----------------------------------------------------------------------
  - name: 'hashicorp/terraform:latest'
    id: 'terraform-plan'
    args:
      - 'plan'
      - '-input=false'
      - '-out=tfplan'
      - '-var=environment=${_ENV}'
      - '-var=project_id=${PROJECT_ID}' 
    dir: 'terraform'

  # ----------------------------------------------------------------------
  # 3. Fase de Despliegue (CD): Aplicación
  # ----------------------------------------------------------------------
  - name: 'hashicorp/terraform:latest'
    id: 'terraform-apply'
    args:
      - 'apply'
      - '-input=false'
      - 'tfplan'
    dir: 'terraform'

# ----------------------------------------------------------------------
# 4. Variables de Sustitución (Cloud Build)
# ----------------------------------------------------------------------
substitutions:
  _TFSTATE_BUCKET: 'dayron-qa-2025-terraform-state'    # Bucket para el backend remoto de Terraform
  _LOGS_BUCKET: 'dayron-qa-2025-cloudbuild-logs'      # Bucket separado para logs de Cloud Build
  _ENV: 'dev'                                         # Entorno por defecto

# ----------------------------------------------------------------------
# 5. Configuración de Logs y Ejecución
# ----------------------------------------------------------------------
logsBucket: 'gs://${_LOGS_BUCKET}'

options:
  logging: GCS_ONLY
  machineType: 'E2_HIGHCPU_8'
  substitution_option: 'ALLOW_LOOSE'  # Permite variables personalizadas
  dynamic_substitutions: true
